name: Automatically Merge Dependabot PRs
on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

  auto-merge-dependabot:
    name: Auto Merge Dependabot PRs
    needs: run-unit-tests
    if: ${{ github.actor == 'dependabot[bot]' && success() }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge PR from Dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: any
          merge-method: rebase

  close-failed-dependabot:
    name: Close Failed Dependabot PRs
    needs: run-unit-tests
    if: ${{ github.actor == 'dependabot[bot]' && !success() }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Close PR
        run: gh pr close "$NUMBER" --comment "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          COMMENT: >
            This pull request was closed due to the unit tests failing.
